### ISSUE TITLE
formatNumber is not a function

### ISSUE THREAD

**Issue by sunviwo** [CaioQuirinoMedeiros/react-native-currency-input#1]
Hi, I'm trying to use the "bonus" ```formatNumber``` to format a TextInput value, but unfortunately getting the following error:
```
TypeError: (0 , _reactNativeCurrencyInput.formatNumber) is not a function
```
A fix would be warmly welcomed. Thks in advance.

**Comment by CaioQuirinoMedeiros** [comment]
@sunviwo, I just realized that I forgot to export the function, I'll fix it soon. Thanks for reporting
