### ISSUE TITLE
how to set placeholder ?

### ISSUE THREAD

**Issue by PokerJava** [CaioQuirinoMedeiros/react-native-currency-input#13]

**Comment by CaioQuirinoMedeiros** [comment]
[Just as you do on a normal TextInput](https://reactnative.dev/docs/0.64/textinput#placeholder)

**Comment by shamshir-glide** [comment]
For FakeCurrencyInput normal TextInput place holder doesn't works

**Comment by ajp8164** [comment]
Created PR for this - https://github.com/CaioQuirinoMedeiros/react-native-currency-input/pull/16
