### ISSUE TITLE
IOS 14.4 - Back button is not appearing

### ISSUE THREAD

**Issue by dineshmatta** [CaioQuirinoMedeiros/react-native-currency-input#3]
When clicking on the currency field in the latest version of Ios, there is no back button appearing so there is no way to come out of num panel.

**Comment by CaioQuirinoMedeiros** [comment]
@dineshmatta this is just a normal TextInput with `keyboardType="numeric"`, what you're reporting is not a bug, if you think it's I'd suggest you to go to react-native issues.

Maybe adding `returnKeyType="done"` will solve your need. Or you can try overwrite the `keyboardType` to achieve what you want.

**Comment by dineshmatta** [comment]
Hey @CaioQuirinoMedeiros 

Yes I figured out the solution and forgot to close the bug, thanks for the reply.
