### ISSUE TITLE
How to show the initial value on CurrencyInput?

### ISSUE THREAD

**Issue by gandarain** [CaioQuirinoMedeiros/react-native-currency-input#4]
Hi, thanks for this library.

I want to ask You about showing the initial value on CurrencyInput.
Let say, I have one CurrencyInput and the initial value is 0, so the Input should be Rp 0.
Is it possible to do that?

**Comment by CaioQuirinoMedeiros** [comment]
Hi @gandarain 
You just need to make sure the initial `value` is 0. If you are using React Hooks it will be something like that:

```ts
const [value, setValue] = React.useState(0) // 0 as initial value

<CurrencyInput
  value={value}
  onChangeValue={setValue}
  unit="Rp"
/>
```

**Comment by gandarain** [comment]
Yeah, I think it was my mistake, thanks for your explanation.
