### ISSUE TITLE
Invalid Prop 'value' of type 'number' supplied to 'ForwardRef(TextInput)', expected 'string

### ISSUE THREAD

**Issue by rlovatto** [CaioQuirinoMedeiros/react-native-currency-input#6]
Hello, 

I'm using the same code as shown as example in the "Usage" section.  The initial value is shown as expected, but I got the error in the subject when I tried to change the value.

**Comment by CaioQuirinoMedeiros** [comment]
@rlovatto that's weird, can you provide us some of your code?

**Comment by rlovatto** [comment]
@CaioQuirinoMedeiros, I realize that I must initialize the state with a number, this way works fine. But I want to initialize with a null value, like below, how can I do that without the error?

const [inputValue, setInputValue] = useState(null);
