### ISSUE TITLE
Skip fraction zeros when start typing

### ISSUE THREAD

**Issue by ugrdursun** [CaioQuirinoMedeiros/react-native-currency-input#7]
Hello,

Thanks for this extremely useful library, appreciate it !

When typing a currency, user needs to add 2 zeros (for dollar) to the end every time if they typing a exact amount and its kinda waste of time and confusing sometimes for users..

I wonder if there is a way to type directly amount and for fractions use dot or comma on the keyboard.

Thanks..

**Comment by CaioQuirinoMedeiros** [comment]
Hi @ugrdursun!

I'm sorry but I did some analysis and came in a conclusion that it'll not be possible, such feature would require a huge and complexity change on the component and I think the current behavior is the most common and appropriate.

**Comment by Bilal-Abdeen** [comment]
Thank you very much for this excellent library. 

I would like to second the need to allow the user to enter an integer. If the user types a decimal, then the number changes to a float number. 

Example: 
User enters: 12 > formatted: 12 (NOT 0.12)
User enters 12.5 > formatted 12.5
