### ISSUE TITLE
Avoid negative number

### ISSUE THREAD

**Issue by rlovatto** [CaioQuirinoMedeiros/react-native-currency-input#8]
Hello,
very nice work.

Is it possible to add the property ignoreNegative to FakeCurrencyInput?

The goal is to forbid the user to type the minus sign. I tried to use minValue={0}, but this not worked.

**Comment by CaioQuirinoMedeiros** [comment]
@rlovatto You actually just reported a bug. Setting `minValue={0}` was supposed to work, but, as you said, it was not.

I just released version 1.0.1 with that fixed. Let me know if you still have any problems.

Thanks!

**Comment by rlovatto** [comment]
It worked, thank you.
